name: Update each commit Dockerfile
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Login to container Registry
    - name: Login to container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build project
    - name: Build and push project
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          ghcr.io/franck-sorel/mk-docs:latest
          ghcr.io/franck-sorel/mk-docs:${{ github.run_number }}
